name: SonarQube Scan

on:
  push:
    branches:
      - main # Change to your branch name

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        with:
          sonar-token: ${{ secrets.SONARQUBE_TOKEN }}
          sonar-project-key: your_project_key
          github-token: ${{ secrets.GITHUB_TOKEN }}
